ot_interpolator:
  ros__parameters:
    map_name: "Berlin"
    n_sectors: 2
    yeet_factor: 1.25
    spline_len: 30
    ot_sector_begin: 0.5

    Overtaking_sector0:
      start: 0
      end: 163
      ot_flag: false

    Overtaking_sector1:
      start: 164
      end: 327
      ot_flag: false
