FROM osrf/ros:humble-desktop
ARG USERNAME
ARG UID=1000
ARG GID=1000

ENV SHELL=/bin/bash

# Fix ROS GPG key expiration issue and re-add repository with updated key
RUN rm -f /etc/apt/sources.list.d/ros2-latest.list \
    && rm -f /etc/apt/sources.list.d/ros2.list \
    && apt-get update && apt-get install -y curl gnupg2 lsb-release \
    && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
    && apt-get update

# Create the user
RUN groupadd --gid $GID $USERNAME \
    && useradd --uid $UID --gid $GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Install packages
RUN apt-get update && apt-get upgrade -y

# install folders are added granularly to avoid unnecessary rebuilds when developing the Dockerfile
ADD .install_utils/linux_req/ /tmp/.install_utils/ 
RUN xargs apt-get install -y < /tmp/.install_utils/linux_req.txt

ADD .install_utils/python_req.txt /tmp/.install_utils/python_req.txt
RUN pip3 install -r /tmp/.install_utils/python_req.txt &&\
    pip3 install quadprog~=0.1.11


# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************
# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME

ADD .install_utils/bashrc/ /tmp/.install_utils/
RUN echo "export USERNAME=$USERNAME" >> /home/$USERNAME/.bashrc &&\
    cat /tmp/.install_utils/.bashrc_git >> /home/$USERNAME/.bashrc &&\
    cat /tmp/.install_utils/.bashrc_forzaeth >> /home/$USERNAME/.bashrc

USER root
# Clean up
RUN rm -rf /tmp/.install_utils
USER $USERNAME

CMD ["/bin/bash"]
